"""Async client for the **UniFi OS** layer (the console itself).

This is deliberately a *separate* client from :class:`~mcp_unifi.clients.unifi.UniFiClient`.
That one wraps ``/proxy/network/api/s/<site>/...`` — every one of its endpoints
*is* the UniFi Network application. When the Network app dies, every single one
of those calls fails, which is precisely when an operator most needs the tool to
say something useful. This client talks to the layer *underneath* Network: the
UniFi OS console, which stays up and answerable while the Network app is
restarting, crash-looping, or migrating its database.

--------------------------------------------------------------------------
THE PROXY SHORT-CIRCUIT TRAP — read this before changing any probe below
--------------------------------------------------------------------------
An **unauthenticated** request to any ``/proxy/network/*`` path returns
**HTTP 401**, generated by the UniFi OS reverse proxy itself. The request never
reaches the Network application. Therefore:

    A 401 from /proxy/network/* proves NOTHING about Network app health.

Reading that 401 as "the app answered, so it must be up" produced a false
"it's recovered" call during the 2026-08-08 outage. The app was still dead.
Every health verdict in this module MUST be derived from an **authenticated**
probe, so that the proxy forwards the request and the *backend's* real state
(502 / 503 / a ``{"meta": {...}}`` status envelope) is what we observe.

--------------------------------------------------------------------------
Endpoint surface, probed live against a UCG-Fiber (UniFi OS 5.1.19,
UniFi Network 10.5.67) on 2026-08-08
--------------------------------------------------------------------------
Verified reachable with **no authentication at all**:

* ``GET /api/system`` → 200, JSON. Console identity + connectivity state:
  ``hardware.shortname``, ``name``, ``mac``, ``deviceState``,
  ``deviceErrorCode``, ``cloudConnected``, ``hasInternet``,
  ``hasInternetLastChanged``, ``remoteAccessEnabled``, ``isSsoEnabled``,
  ``debugEnabled``, ``isOrHasGatewayInLAN``, ``isSingleUser``, ``uidb``.
  NOTE: carries **no CPU / memory / disk metrics** on this firmware.
* ``GET /api/apps`` → 200, ``{"apps": [...], "controllers": [...]}``.
* ``GET /status`` → 200, but **HTML**, not JSON. It is the console shell with a
  ``window.UNIFI_OS_MANIFEST = {...}`` blob inlined in a ``<script>`` tag. We
  do not parse it; ``/api/system`` carries the same identity as real JSON.

Verified requiring the API key (proxy-gated, 401 without it):

* ``GET /proxy/network/status`` → 200 + ``{"meta": {"rc", "server_version",
  "server_running", "db_migrating", "up", "app_context_status",
  "app_context_message"}, "data": []}``. **This is the flagship health
  signal** — the Network app reports its own state here, and it answers even
  while the app's ``/api/s/<site>/*`` routes are returning 503.

Verified present but requiring a **console session** (401 with the API key —
the Network API key does not authenticate the UniFi OS layer):

* ``GET /api/firmware/update``, ``GET /api/users/self``,
  ``GET /api/notifications``.

Verified **absent** on this firmware (all 404 — do not reintroduce them
without re-probing): ``/api/health``, ``/api/info``, ``/api/storage``,
``/api/system/storage``, ``/api/system/info``, ``/api/os``, ``/api/status``,
``/api/firmware``, ``/api/sysinfo``, ``/api/settings``, ``/api/system/health``,
``/api/updates``, ``/api/disks``, ``/api/system/disks``, ``/api/hardware``,
``/api/ustorage``, ``/api/logs``, ``/api/diagnostics``.

**There is no disk-usage endpoint on this UniFi OS build.** A disk-full
diagnosis has to come from the console UI or SSH, not from this API. We report
that honestly rather than inventing a metric.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

logger = logging.getLogger("mcp_unifi.client.unifi_os")

#: Console-session login endpoint. POST-only (GET answers 405, confirming the
#: route exists). Body is ``{"username", "password"}``; a successful login sets
#: a ``TOKEN`` cookie and returns an ``X-Updated-CSRF-Token`` response header
#: that must be echoed on subsequent state-changing calls.
LOGIN_PATH = "/api/auth/login"

#: Unauthenticated console identity endpoint (verified 200 with no auth).
SYSTEM_PATH = "/api/system"

#: Installed-application inventory (verified 200 with no auth).
APPS_PATH = "/api/apps"

#: The Network application's own status endpoint. Proxy-gated: requires the
#: API key. See the module docstring's short-circuit warning.
NETWORK_STATUS_PATH = "/proxy/network/status"

#: Firmware/update state. Requires a console session, NOT the API key.
FIRMWARE_UPDATE_PATH = "/api/firmware/update"


class UniFiOSError(RuntimeError):
    """Raised on a transport failure talking to the UniFi OS console."""


class UniFiOSAuthError(UniFiOSError):
    """Raised when a console-session call is made without usable credentials."""


class ProbeResult:
    """One HTTP probe's outcome, in a form the health tools can reason about.

    Deliberately captures *either* a status code *or* a transport error, never
    raises. Health reporting must survive the thing it is reporting on being
    broken.
    """

    __slots__ = ("body", "error", "path", "status")

    def __init__(
        self,
        path: str,
        *,
        status: int | None = None,
        body: Any = None,
        error: str | None = None,
    ) -> None:
        self.path = path
        self.status = status
        self.body = body
        self.error = error

    @property
    def reachable(self) -> bool:
        """True when the host answered at all (any HTTP status counts)."""
        return self.status is not None

    def as_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"path": self.path, "status": self.status}
        if self.error:
            out["error"] = self.error
        return out


class UniFiOSClient:
    """Thin async client for the UniFi OS console layer.

    Two credential paths, used for different endpoints:

    * ``api_key`` (``X-API-Key``) — authenticates against the Network app
      *through* the UniFi OS proxy. Required for
      :meth:`probe_network_app_status`. Does **not** authenticate UniFi OS's
      own ``/api/*`` endpoints.
    * ``username`` / ``password`` — a console local-admin login that yields a
      session cookie, unlocking the session-gated UniFi OS endpoints. Optional;
      every method that needs it degrades with a clear
      :class:`UniFiOSAuthError` rather than a bare 401 or a stack trace.

    Args:
        host: Gateway IP or hostname (no scheme).
        api_key: Network local API key. Optional but required for the Network
            app status probe.
        port: HTTPS port (default 443).
        username: Console local-admin username. Optional.
        password: Console local-admin password. Optional.
        verify_ssl: Verify the console's TLS cert. Self-hosted gateways ship a
            self-signed cert, so this defaults to False.
        timeout: Per-request timeout in seconds. Kept short — a health probe
            that hangs is worse than one that reports a timeout.
    """

    def __init__(
        self,
        host: str,
        api_key: str = "",
        port: int = 443,
        username: str = "",
        password: str = "",
        verify_ssl: bool = False,
        timeout: float = 10.0,
    ) -> None:
        self.host = host
        self.port = port
        self._api_key = api_key
        self._username = username
        self._password = password
        self._base = f"https://{host}:{port}"
        self._csrf_token: str | None = None
        self._client = httpx.AsyncClient(
            timeout=timeout,
            verify=verify_ssl,
            headers={"Accept": "application/json"},
            limits=httpx.Limits(max_connections=5, max_keepalive_connections=2),
            follow_redirects=False,
        )

    async def aclose(self) -> None:
        await self._client.aclose()

    @property
    def has_session_credentials(self) -> bool:
        """True when both a console username and password were configured."""
        return bool(self._username and self._password)

    # ------------------------------------------------------------------
    # Probing (never raises — returns ProbeResult)
    # ------------------------------------------------------------------

    async def _probe(
        self,
        path: str,
        *,
        with_api_key: bool = False,
        with_session: bool = False,
    ) -> ProbeResult:
        """GET ``path`` and capture the outcome without raising.

        Transport failures (DNS, TCP refused, TLS, timeout) become a
        ``ProbeResult`` with ``status=None`` and an ``error`` string. Any HTTP
        response — including 4xx and 5xx — is a successful probe: the status
        code *is* the signal we are after.
        """
        headers: dict[str, str] = {}
        if with_api_key and self._api_key:
            headers["X-API-Key"] = self._api_key
        if with_session and self._csrf_token:
            headers["X-CSRF-Token"] = self._csrf_token
        try:
            resp = await self._client.get(f"{self._base}{path}", headers=headers)
        except httpx.HTTPError as exc:
            # Class name, not str(exc) — httpx embeds the full URL in some
            # messages and the API key never belongs in a log line.
            return ProbeResult(path, error=f"{type(exc).__name__}: {exc!s}"[:200])
        body: Any = None
        if resp.content:
            try:
                body = resp.json()
            except ValueError:
                # /status answers HTML, and error pages sometimes do too.
                body = None
        return ProbeResult(path, status=resp.status_code, body=body)

    async def probe_console(self) -> ProbeResult:
        """Probe the UniFi OS console itself via unauthenticated ``/api/system``.

        A transport error here means the console is unreachable (box down,
        network partition, wrong host). Any HTTP status means UniFi OS answered.
        """
        return await self._probe(SYSTEM_PATH)

    async def probe_network_app_status(self) -> ProbeResult:
        """Probe the Network application's own status endpoint, **authenticated**.

        Sends ``X-API-Key`` so the UniFi OS proxy forwards the request to the
        Network backend instead of short-circuiting it with a 401. See the
        module docstring: an unauthenticated probe here is meaningless.
        """
        return await self._probe(NETWORK_STATUS_PATH, with_api_key=True)

    async def probe_apps(self) -> ProbeResult:
        """Probe the installed-application inventory (unauthenticated)."""
        return await self._probe(APPS_PATH)

    async def probe_network_serving(self, site: str = "default") -> ProbeResult:
        """Probe a real Network API route to prove the app is actually serving.

        ``/proxy/network/status`` is the app's *self-report*, and on this
        firmware a healthy app reports almost nothing (see
        :mod:`mcp_unifi.modules.network.console` for the envelope shapes). This
        probe hits ``stat/sysinfo`` — an ordinary read that every Network tool
        depends on — so the health verdict can be grounded in evidence that the
        application answered a real query, not merely in the absence of a
        failure flag.
        """
        return await self._probe(f"/proxy/network/api/s/{site}/stat/sysinfo", with_api_key=True)

    # ------------------------------------------------------------------
    # Console session auth (optional credential path)
    # ------------------------------------------------------------------

    async def login(self) -> None:
        """Establish a console session from ``username`` / ``password``.

        The session cookie is stored on the underlying httpx client's cookie
        jar and reused for subsequent calls; the CSRF token from
        ``X-Updated-CSRF-Token`` is retained for state-changing requests.

        Raises:
            UniFiOSAuthError: no credentials configured, or the console
                rejected them.
            UniFiOSError: transport failure reaching the console.
        """
        if not self.has_session_credentials:
            raise UniFiOSAuthError(
                "UniFi OS console credentials are not configured. Set "
                "UNIFI_OS_USERNAME and UNIFI_OS_PASSWORD to enable "
                "console-session tools. The Network API key does not "
                "authenticate the UniFi OS layer."
            )
        try:
            resp = await self._client.post(
                f"{self._base}{LOGIN_PATH}",
                json={"username": self._username, "password": self._password},
            )
        except httpx.HTTPError as exc:
            raise UniFiOSError(f"UniFi OS login transport failure: {type(exc).__name__}") from exc
        if resp.status_code in (401, 403):
            raise UniFiOSAuthError(
                f"UniFi OS console rejected the configured credentials (HTTP {resp.status_code})."
            )
        if resp.status_code >= 400:
            raise UniFiOSError(f"UniFi OS login returned HTTP {resp.status_code}.")
        token = resp.headers.get("X-Updated-CSRF-Token")
        if token:
            self._csrf_token = token

    async def ensure_session(self) -> None:
        """Log in if no session cookie is present yet. Idempotent."""
        if self._client.cookies.get("TOKEN"):
            return
        await self.login()

    async def get_session_json(self, path: str) -> Any:
        """GET a session-gated UniFi OS endpoint, logging in on demand.

        Retries once after a fresh login if the console answers 401 (the
        session expired between calls).

        Raises:
            UniFiOSAuthError: credentials absent or rejected.
            UniFiOSError: transport failure or a non-2xx response.
        """
        await self.ensure_session()
        result = await self._probe(path, with_session=True)
        if result.status == 401:
            # Session expired mid-flight — one clean re-login, then re-probe.
            await self.login()
            result = await self._probe(path, with_session=True)
        if not result.reachable:
            raise UniFiOSError(f"UniFi OS GET {path} failed: {result.error}")
        if result.status in (401, 403):
            raise UniFiOSAuthError(
                f"UniFi OS console rejected the session for {path} (HTTP {result.status})."
            )
        if result.status is not None and result.status >= 400:
            raise UniFiOSError(f"UniFi OS GET {path} returned HTTP {result.status}.")
        return result.body
