apiVersion: v2
name: mcp-unifi
description: MCP server for self-hosted UniFi gateway management
type: application
version: 0.1.1
appVersion: "0.5.1"
home: https://github.com/pete-builds/mcp-unifi
sources:
  - https://github.com/pete-builds/mcp-unifi
keywords:
  - mcp
  - unifi
  - homelab
maintainers:
  - name: Pete Stergion
    url: https://github.com/pete-builds
